<!-- sidebar.inc -->
<aside class="sidebar">
  <section>
    <h1>Topics</h1>
    <ul>
      <li class="post">
	  <a href="/">Home: Home page</a>
      </li>
      <li class="post">
	  <a href="/news">News: Latest information</a>
      </li>
      <li class="post">
	  <a href="/policies">Policies: Our processes and guidelines</a>
      </li>
      <li class="post">
	  <a href="/community">Community: Mailing lists, blog, bug reports, etc.</a>
      </li>
      <li class="post">
	  <a href="/fips">FIPS: FIPS-140 validation</a>
      </li>
      <li class="post">
	  <a href="/support">Support: Commercial support and contracting</a>
      </li>
    </ul>
  </section>
</aside>
<!-- end -->

