<!-- sidebar.inc -->
<aside class="sidebar">
  <section>
    <h1>Topics</h1>
    <ul>
      <li>
	<a href="/news/advisories">Security Advisories</a>
      </li>
      <li>
	<a href="/news/vulnerabilities">Vulnerabilities</a>
      </li>
      <li>
	<a href="/news/newsflash">Newsflash</a>
      </li>
      <li>
	<a href="/news/changelogs">Changelogs</a>
      </li>
    </ul>
  </section>
</aside>
<!-- end -->
