<!-- banner.inc -->
<header role="banner">
  <hgroup>
    <h1>
      <a href="/">
	<img src="/img/openssl.png" alt="OpenSSL"></img>
      </a>
    </h1>
  </hgroup>
</header>

<nav role="navigation">
  <form action="https://www.google.com/search" method="get">
    <fieldset role="search">
      <input type="hidden" name="q" value="site:www.openssl.org" />
      <input class="search" type="text" name="q" results="0" placeholder="Search"/>
    </fieldset>
  </form>
  <ul class="main-navigation">
    <li><a href="/" title="Home page">Home</a></li>
    <li><a href="/downloads" title="Source code">Downloads</a></li>
    <li><a href="/news" title="Latest information">News</a></li>
    <li><a href="/policies" title="How we operate">Policies</a></li>
    <li><a href="/community" title="Mailing lists, blog, bug reports, etc.">Community</a></li>
    <li><a href="/fips" title="FIPS-140 validation">FIPS</a></li>
    <li><a href="/support" title="Commercial support and contracting">Support</a></li>
  </ul>
  </nav>
<!-- end -->
